// <auto-generated />
using System;
using Asambleas.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Asambleas.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260321002325_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asambleas.Features.Asambleas.Entities.Asamblea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("HorarioInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VentanaInscripcionFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VentanaInscripcionInicio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("asambleas", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Asambleas.Entities.VentanaHoraria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<Guid>("AsambleaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AsambleaId");

                    b.ToTable("ventanas_horarias", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDomelecVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LdapUsername")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Cuil")
                        .IsUnique();

                    b.HasIndex("Dni");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.DeclaracionJurada.Entities.DeclaracionJurada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorasTotalesOcupadas")
                        .HasColumnType("integer");

                    b.Property<string>("JurisdiccionActual")
                        .HasColumnType("text");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasoActual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TrabajaEnOtraJurisdiccion")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.ToTable("declaraciones_juradas", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.DeclaracionJurada.Entities.EmpleoActual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeclaracionJuradaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Establecimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HorarioJueves")
                        .HasColumnType("text");

                    b.Property<string>("HorarioLunes")
                        .HasColumnType("text");

                    b.Property<string>("HorarioMartes")
                        .HasColumnType("text");

                    b.Property<string>("HorarioMiercoles")
                        .HasColumnType("text");

                    b.Property<string>("HorarioSabado")
                        .HasColumnType("text");

                    b.Property<string>("HorarioViernes")
                        .HasColumnType("text");

                    b.Property<int>("Horas")
                        .HasColumnType("integer");

                    b.Property<string>("Jurisdiccion")
                        .HasColumnType("text");

                    b.Property<string>("SituacionRevista")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeclaracionJuradaId");

                    b.ToTable("empleos_actuales", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Designacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AsambleaId")
                        .HasColumnType("uuid");

                    b.Property<string>("CertificadoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaConfirmacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRechazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Instancia")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AsambleaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("VacanteId");

                    b.ToTable("designaciones", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Impugnacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesignacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReclamanteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolucion")
                        .HasColumnType("text");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignacionId");

                    b.HasIndex("ReclamanteId");

                    b.ToTable("impugnaciones", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Postulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Puntaje")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VacanteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VacanteId");

                    b.HasIndex("DocenteId", "VacanteId")
                        .IsUnique();

                    b.ToTable("postulaciones", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Docentes.Entities.DocenteProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadRenuncias")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeclaracionJuradaPresentada")
                        .HasColumnType("boolean");

                    b.Property<bool>("Embarazo")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoRevista")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("Inhabilitado")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoInhabilitacion")
                        .HasColumnType("text");

                    b.Property<string>("NivelEducativo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Puntaje")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("docente_profiles", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Listados.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Entidad");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Listados.Entities.ListadoOficial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Anio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("listados_oficiales", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Listados.Entities.PostulanteListado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ListadoOficialId")
                        .HasColumnType("uuid");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<decimal>("Puntaje")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("ListadoOficialId");

                    b.ToTable("postulantes_listado", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Vacantes.Entities.Establecimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoFuncional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoFuncional")
                        .IsUnique();

                    b.ToTable("establecimientos", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Vacantes.Entities.Vacante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AsambleaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EstablecimientoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Horas")
                        .HasColumnType("integer");

                    b.Property<int>("Modulos")
                        .HasColumnType("integer");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("TipoCargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AsambleaId");

                    b.HasIndex("EstablecimientoId");

                    b.ToTable("vacantes", (string)null);
                });

            modelBuilder.Entity("Asambleas.Features.Asambleas.Entities.VentanaHoraria", b =>
                {
                    b.HasOne("Asambleas.Features.Asambleas.Entities.Asamblea", "Asamblea")
                        .WithMany("VentanasHorarias")
                        .HasForeignKey("AsambleaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asamblea");
                });

            modelBuilder.Entity("Asambleas.Features.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("Asambleas.Features.Auth.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asambleas.Features.DeclaracionJurada.Entities.DeclaracionJurada", b =>
                {
                    b.HasOne("Asambleas.Features.Auth.Entities.User", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("Asambleas.Features.DeclaracionJurada.Entities.EmpleoActual", b =>
                {
                    b.HasOne("Asambleas.Features.DeclaracionJurada.Entities.DeclaracionJurada", "DeclaracionJurada")
                        .WithMany("EmpleosActuales")
                        .HasForeignKey("DeclaracionJuradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeclaracionJurada");
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Designacion", b =>
                {
                    b.HasOne("Asambleas.Features.Asambleas.Entities.Asamblea", "Asamblea")
                        .WithMany()
                        .HasForeignKey("AsambleaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Auth.Entities.User", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Vacantes.Entities.Vacante", "Vacante")
                        .WithMany()
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asamblea");

                    b.Navigation("Docente");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Impugnacion", b =>
                {
                    b.HasOne("Asambleas.Features.Designaciones.Entities.Designacion", "Designacion")
                        .WithMany("Impugnaciones")
                        .HasForeignKey("DesignacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Auth.Entities.User", "Reclamante")
                        .WithMany()
                        .HasForeignKey("ReclamanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Designacion");

                    b.Navigation("Reclamante");
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Postulacion", b =>
                {
                    b.HasOne("Asambleas.Features.Auth.Entities.User", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Vacantes.Entities.Vacante", "Vacante")
                        .WithMany()
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("Asambleas.Features.Docentes.Entities.DocenteProfile", b =>
                {
                    b.HasOne("Asambleas.Features.Auth.Entities.User", "User")
                        .WithOne("DocenteProfile")
                        .HasForeignKey("Asambleas.Features.Docentes.Entities.DocenteProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Asambleas.Features.Listados.Entities.PostulanteListado", b =>
                {
                    b.HasOne("Asambleas.Features.Auth.Entities.User", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Listados.Entities.ListadoOficial", "ListadoOficial")
                        .WithMany("Postulantes")
                        .HasForeignKey("ListadoOficialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docente");

                    b.Navigation("ListadoOficial");
                });

            modelBuilder.Entity("Asambleas.Features.Vacantes.Entities.Vacante", b =>
                {
                    b.HasOne("Asambleas.Features.Asambleas.Entities.Asamblea", "Asamblea")
                        .WithMany()
                        .HasForeignKey("AsambleaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Asambleas.Features.Vacantes.Entities.Establecimiento", "Establecimiento")
                        .WithMany("Vacantes")
                        .HasForeignKey("EstablecimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asamblea");

                    b.Navigation("Establecimiento");
                });

            modelBuilder.Entity("Asambleas.Features.Asambleas.Entities.Asamblea", b =>
                {
                    b.Navigation("VentanasHorarias");
                });

            modelBuilder.Entity("Asambleas.Features.Auth.Entities.User", b =>
                {
                    b.Navigation("DocenteProfile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Asambleas.Features.DeclaracionJurada.Entities.DeclaracionJurada", b =>
                {
                    b.Navigation("EmpleosActuales");
                });

            modelBuilder.Entity("Asambleas.Features.Designaciones.Entities.Designacion", b =>
                {
                    b.Navigation("Impugnaciones");
                });

            modelBuilder.Entity("Asambleas.Features.Listados.Entities.ListadoOficial", b =>
                {
                    b.Navigation("Postulantes");
                });

            modelBuilder.Entity("Asambleas.Features.Vacantes.Entities.Establecimiento", b =>
                {
                    b.Navigation("Vacantes");
                });
#pragma warning restore 612, 618
        }
    }
}
